after_script:
- bash <(curl -s https://codecov.io/bash)
dotnet: 2.2.1
env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
language: csharp
mono: none
notifications:
  slack:
    on_failure: always
    on_pull_requests: true
    on_success: always
    rooms:
      secure: P8XzI2YqKJV6lu3qpjXZiIB9AaqJzKAw8SdH48P0M97tP1vVZXRPjgFjS2INnDBbq05TcZ7kvG0puL9w3JuAdMA6URuH6VPxbt9NuJaQyb7c1PRyIrmoxZN8nKBYYKvGDD1WpzBZXvBB49MOZC7WRfoRDzF3smRiWCbPnUTiTnvOG61c2V48b1/QRtzhx84HNItKys45yPKchP2F7a5nJ4s9oHjP37gHia3X9c1g9NkejT5f2QM/DOa6n/7Vue/9tn57PNmkVYzZNiqQAqXo3V3uPIjRelAtA6zVIpCYLLkgJh73PgqTGVy5p/gVnjy4N7NP2T2cnqQn0r/buobFd06lf22shFbwPdLia+wRTJzpv1x2NBibToe7Ue19naCIwYoZ54kc93HFugJt1BG1tf86YdGtzxIu5rtYK33eydm2XQVK1/SupOqhSb80Q/IMqTmJY86LOypPe9qARxIXG7q6CmJqf7E+PfdUlXs8JuEICpOXJNwE8ShdidMVfi/Qltzh5ZISGXut5coWEg2duvReerThHyd9FNH64uUgmzGwuI+EVd5XyoUzOvgE53gEu1IDDskVbSflfyWmO5D3UvMLuHGPPNqLfPGWzSkaPIQanUyXIc+Jxw8yBo0pnThGI9XzCkSD7/8ZqJGw8tw8a3YSnLCbgUSrVMGem7XkQJ4=
script:
- dotnet restore
- dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:Threshold=0
solution: All.sln
